# Generated by Django 4.1.13 on 2024-03-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Eid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=200)),
                ('Eemail', models.EmailField(max_length=254)),
                ('Econtact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
