# Generated by Django 4.1.13 on 2024-03-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_employee_econtact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Econtact',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
