# Generated by Django 4.1.13 on 2024-03-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employee_id_alter_employee_econtact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Eid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
