# Generated by Django 4.1.13 on 2024-03-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_employee_id_alter_employee_eid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
