# Generated by Django 4.1.13 on 2024-03-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
